export const tableData = {
    sep_2023: [{
      name: "Ram Kumar",
      category: "Bank Transfer",
      type: "credit",
      date: "12-09-2023",
      amount: "Rs.1504",
      bank: "SBI",
    },
    {
      name: "Lulu international",
      category: "shopping",
      type: "debit",
      date: "12-09-2023",
      amount: "Rs.1256",
      bank: "ICICI",
    },
    {
      name: "ElectroMen Market",
      category: "shopping",
      type: "debit",
      date: "01-09-2023",
      amount: "Rs.2604",
      bank: "SBI",
    },
    {
      name: "Paragon",
      category: "food",
      type: "debit",
      date: "12-09-2023",
      amount: "Rs.1134",
      bank: "SBI",
    },
    {
      name: "Chiyang",
      category: "food",
      type: "debit",
      date: "15-09-2023",
      amount: "Rs.834",
      bank: "SBI",
    },
    {
      name: "Jaison",
      category: "Bank Transfer",
      type: "credit",
      date: "11-09-2023",
      amount: "Rs.1300",
      bank: "SBI",
    },
    {
      name: "Jaison",
      category: "Bank Transfer",
      type: "credit",
      date: "11-09-2023",
      amount: "Rs.1230",
      bank: "ICICI",
    },
    {
      name: "Just tiffins",
      category: "food",
      type: "debit",
      date: "11-09-2023",
      amount: "Rs.1000",
      bank: "SBI",
    },
    {
      name: "Kumar varma",
      category: "Bank Transfer",
      type: "credit",
      date: "11-09-2023",
      amount: "Rs.534",
      bank: "ICICI",
    }
    ],
    aug_2023: [
      {
        name: "Lulu international",
        category: "shopping",
        type: "debit",
        date: "12-08-2023",
        amount: "Rs.1256",
        bank: "ICICI",
      },
      {
        name: "Jaison",
        category: "Bank Transfer",
        type: "credit",
        date: "11-08-2023",
        amount: "Rs.1300",
        bank: "SBI",
      },
      {
        name: "Paragon",
        category: "food",
        type: "debit",
        date: "12-08-2023",
        amount: "Rs.1134",
        bank: "SBI",
      },
      {
        name: "Chiyang",
        category: "food",
        type: "debit",
        date: "15-08-2023",
        amount: "Rs.834",
        bank: "SBI",
      },
      {
        name: "Kumar varma",
        category: "Bank Transfer",
        type: "credit",
        date: "11-08-2023",
        amount: "Rs.534",
        bank: "ICICI",
      },
      {
        name: "Jaison",
        category: "Bank Transfer",
        type: "credit",
        date: "11-08-2023",
        amount: "Rs.1230",
        bank: "ICICI",
      },
      {
        name: "ElectroMen Market",
        category: "shopping",
        type: "debit",
        date: "01-08-2023",
        amount: "Rs.2604",
        bank: "SBI",
      },
      {
        name: "Ram Kumar",
        category: "Bank Transfer",
        type: "credit",
        date: "12-08-2023",
        amount: "Rs.1504",
        bank: "SBI",
      },
      {
        name: "Just tiffins",
        category: "food",
        type: "debit",
        date: "11-08-2023",
        amount: "Rs.1000",
        bank: "SBI",
      }
      ]
};